live_config_reload = true

import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach --index 0 --create"]


[font]
  size = 12.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
  family = "HackGen Console NF"
  style = "Regular"

[font.bold]
  family = "HackGen Console NF"
  style = "Bold"

[font.italic]
  family = "HackGen Console NF"
  style = "Italic"
